# Generated by Django 4.2.28 on 2026-02-22 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('last_reviewed_sha', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_sha', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=20)),
                ('comments_posted', models.PositiveIntegerField(default=0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('fallback_comment_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('upstream_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('installation_id', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.repository'),
        ),
        migrations.CreateModel(
            name='ReviewRunFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changes', models.PositiveIntegerField(default=0)),
                ('previous_filename', models.CharField(blank=True, max_length=500)),
                ('patch', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_file_snapshots', to='reviews.reviewrun')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['run', 'position'], name='reviews_rev_run_id_f95202_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewRunComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('line', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default='RIGHT', max_length=5)),
                ('body', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_comments', to='reviews.reviewrun')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['run', 'position'], name='reviews_rev_run_id_322734_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reviewrun',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_b640c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('pull_request', 'idempotency_key'), name='uniq_reviewrun_idempotency_per_pr'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
    ]
